apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: argocd-vks-cluster
  namespace: demo
  labels:
    tkg-cluster-selector: argocd-vks-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.3.0
    version: v1.32.0---vmware.6-fips-vkr.2
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: homelab-default-sp
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: argocd-vks-nodepool
          replicas: 1
